version: '3.8'

services:
  # Laravel development application
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: smartop-app-dev
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - XDEBUG_MODE=develop,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
    depends_on:
      - mysql
      - redis
    networks:
      - smartop-network
    restart: unless-stopped

  # MySQL database
  mysql:
    image: mysql:8.0
    container_name: smartop-mysql-dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smartop_dev
      MYSQL_USER: smartop
      MYSQL_PASSWORD: password
    volumes:
      - mysql_dev_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - smartop-network
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7.0-alpine
    container_name: smartop-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - smartop-network
    restart: unless-stopped

  # Mail service for development
  mailpit:
    image: axllent/mailpit
    container_name: smartop-mail-dev
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - smartop-network
    restart: unless-stopped

  # PhpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: smartop-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: smartop
      PMA_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - smartop-network
    restart: unless-stopped

  # Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: smartop-redis-commander
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis
    networks:
      - smartop-network
    restart: unless-stopped

volumes:
  mysql_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  smartop-network:
    driver: bridge