groups:
  - name: smartop.rules
    rules:
      # Application alerts
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }} seconds"

      - alert: ApplicationDown
        expr: up{job="smartop-app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "SmartOP application is down"
          description: "Application has been down for more than 1 minute"

      # Database alerts
      - alert: MySQLDown
        expr: up{job="mysql"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "MySQL database is down"
          description: "MySQL has been down for more than 1 minute"

      - alert: MySQLHighConnections
        expr: mysql_global_status_threads_connected / mysql_global_variables_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "MySQL connection usage is high"
          description: "MySQL connection usage is {{ $value | humanizePercentage }}"

      - alert: MySQLSlowQueries
        expr: rate(mysql_global_status_slow_queries[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "MySQL slow queries detected"
          description: "MySQL slow query rate is {{ $value }} queries per second"

      # Redis alerts
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis has been down for more than 1 minute"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_config_maxmemory > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis memory usage is {{ $value | humanizePercentage }}"

      # System alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

      - alert: LowDiskSpace
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

      # Queue alerts
      - alert: HighQueueSize
        expr: laravel_queue_size > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Queue size is high"
          description: "Queue {{ $labels.queue }} has {{ $value }} jobs pending"

      - alert: QueueWorkerDown
        expr: laravel_queue_workers == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "No queue workers running"
          description: "All queue workers are down for queue {{ $labels.queue }}"

      # Application-specific alerts
      - alert: HighMachineFailureRate
        expr: rate(smartop_machine_failures_total[1h]) > 0.1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High machine failure rate"
          description: "Machine failure rate is {{ $value }} failures per hour"

      - alert: ControlListOverdue
        expr: smartop_overdue_control_lists > 5
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Control lists are overdue"
          description: "{{ $value }} control lists are overdue"

      - alert: MaintenanceOverdue
        expr: smartop_overdue_maintenance > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Maintenance is overdue"
          description: "{{ $value }} machines have overdue maintenance"